package io.github.yoglappland.spectralization.optics.compiler;

public enum ScalarSolverKind {
    NONE,
    TOPOLOGICAL_DAG,
    FEEDBACK_SCC_EXACT,
    FEEDBACK_CHORD,
    PROFILE_STATE_EXACT,
    PROFILE_COLLAPSED_EXACT,
    MIXED_REGION,
    NO_EXACT_SOLVER,
    WEIGHTED_BFS_ATTENTION,
    MAGNITUDE_BUCKET,
    RESIDUAL_CORRECTION,
    LOOP_MACRO,
    SYMMETRY_REDUCTION,
    DEBUG_ORACLE
}
